### ISSUE TITLE
Prebuild step not firing

### ISSUE THREAD

**Issue by DenisBiondic** [stajs/SpecFlow.NetCore#1]
Solution works great, and is a clever workaround until SpecFlow catches up. I only have a problem binding "dnx specflow-dnx" as a prebuid script step. It works fine when run with command line, but not automatically in VS. How did you get the prebuild step to fire for you?

**Comment by stajs** [comment]
Ah, yeah, the prebuild is not working for me either in VS :sob:

I think it's a matter of DNX progressing so fast and the VS tooling not keeping up. I _think_ in previous DNX betas, having a `prebuild` step in your `project.json` worked from inside VS. However, I think at that stage I was using gulp tasks which was probably more supported for being run inside the VS Task Runner...? But since then, I got too annoyed at gulp, switched back to C# and now running against RC1, too many things have changed for me to hazard a guess as to the problem.

I was planning on creating a smaller reproduction and finding the best place to file an issue with the DNX/VS teams, but haven't got around to it yet.

PS, glad it is working for you (at least from the command line). Out of curiousity, did the [sample](https://github.com/stajs/SpecFlow.Dnx/tree/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final) help?

**Comment by stajs** [comment]
I've updated the README to reflect this.

**Comment by DenisBiondic** [comment]
Yes, it helped, it was the first thing I opened :+1:

**Comment by stajs** [comment]
As of RC1, [you have to "produce outputs"](https://github.com/aspnet/Home/issues/432) to pipe the build through `dnu`:

![image](https://cloud.githubusercontent.com/assets/2253814/11394282/f096a800-93c8-11e5-8b62-03d80cfb1b0e.png)

![image](https://cloud.githubusercontent.com/assets/2253814/11394338/4471d1a2-93c9-11e5-94d1-ac2744f77d84.png)

I must have flicked that setting on at some stage, and not realized the connection when I recreated the solution.

**Comment by smudge202** [comment]
I know the issue is closed, but can you add the note about "Produce outputs on build" to the readme please? (It still contains the workaround info regarding manual builds).

EDIT: Awesome job on this project. Will help where necessary/possible.

**Comment by stajs** [comment]
Good idea, I've updated the README for "produce outputs".

And, thanks! :heart: More than happy to accept help for anything you think needs improving.
