### ISSUE TITLE
Figure out if moving to net40 is a good thing

### ISSUE THREAD

**Issue by stajs** [stajs/SpecFlow.NetCore#10]
Yeah, best issue title ever. This is just a placeholder so I remember to do some digging.

[For `alpha8`](https://www.nuget.org/packages/SpecFlow.Dnx/1.0.0-alpha8), the dependencies are this:

![image](https://cloud.githubusercontent.com/assets/2253814/11585715/df2025ae-9ad2-11e5-9641-00d35c11ca29.png)

[For `alpha9`](https://www.nuget.org/packages/SpecFlow.Dnx/1.0.0-alpha9), they became this:

![image](https://cloud.githubusercontent.com/assets/2253814/11585736/f8d40e16-9ad2-11e5-8ec3-31d17ebd5c1b.png)

Yes I know, `dnx46` is based on full .NET Framework 4.6. I wonder if I need to have multiple TFMs in the library now.

**Comment by smudge202** [comment]
lol. Interesting issue.

The only problem I foresee with the `net40` tfm is people trying to use it outside of dnx (which the library might appear to support). Being agile, I suggest we wait and see if anyone raises an issue as such. Otherwise, I don't see their being any problems.

I'd have preferred to use a `netstandard1.*` (`dotnet5.*+1`) moniker but our dependencies don't support it. I suspect there are actually only a few TFM's that we _can_ use due to the dependencies. (.Net3.5 - .Net4.5.1?).

**Comment by stajs** [comment]
I think I just had an allergic reaction to seeing .NET 4 in this shiny new DNX library.

What dependencies prevent `netstandard`? You'd think I'd know, but I don't think we have any blockers...?

I think we can move to a `netstandard` TFM when it's available. [It's not working yet](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) ([waiting on NuGet tooling](https://github.com/dotnet/corefx/issues/4367)), but looks like they are aiming for support in RC2. The current guidance is:

> The earliest .NET Framework to support a .NET Platform Standard version is .NET Framework 4.5.

... which is `netstandard1.1`, but I'd rather limit to just 4.5.1/4.5.2 with `netstandard1.2`.

**Comment by smudge202** [comment]
You can use `netstandard` in rc1 under the caveat it's called `dotnet`, the major is `5` instead of `1`, and the minor is 1 higher than the `netstandard` version. :laughing:

What that translates to is actually simpler than I've described:

`netstandard1.0` -> `dotnet5.1`
`netstandard1.1` -> `dotnet5.2`
etc.

However, you'll find SpecFlow 1.9.0 doesn't support any of these currently (hit this issue last night when implementing the `dnx451` support). SpecFlow doesn't appear to support much in the way of `netcore` and therefore isn't available to the netstandard tfm's.

**Comment by stajs** [comment]
Well, if I haven't looked at this yet, I don't care about it enough. Can always reopen to investigate later.
