### ISSUE TITLE
README Update for xunit tips

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#2]
As per my comment on a previous issue, it would be good to get the `Produce output on builds` info added to the readme. In addition, I think the follow two tips would be great:

To automate testing of your specs:
- In `project.json`, add a dependency to `xunit.runner.dnx` (at time of writing, version `2.1.0-rc1-build204`).
- Add a second command (in addition to the one used by the `prebuild` element) as follows:

`"test": "xunit.runner.dnx"`

This will make your specs appear in test explorer.

The overall output will be along the lines of:

``` json
{
    "version": "1.0.0-*",
    "commands": {
        "create-specs": "SpecFlow.Dnx",
        "test": "xunit.runner.dnx"
    },
    "scripts": {
        "prebuild": "dnx create-specs"
    },
    "frameworks": {
        "dnx46": {
            "dependencies": {
                "SpecFlow.Dnx": "1.0.0-alpha8",
                "xunit": "2.1.0",
                "xunit.runner.dnx": "2.1.0-rc1-build204"
            }
        }
    }
}
```

The above is obvious if you've ever done work with DNX in the past, but for people entering the arena it would be helpful I'm sure.

**Comment by stajs** [comment]
Okay, I saw your other comment first, and have updated the README for "produce outputs".

Good idea for the tips. Did you want to submit a PR (then you'll get the credit)? If so, I suggest referencing the sample `project.json`, in particular [not including the dependencies as framework dependencies](https://github.com/stajs/SpecFlow.Dnx/blob/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final/Sample.Website.Tests/project.json#L13) (otherwise each framework has to independently reference).

**Comment by smudge202** [comment]
Yup, I'll PR over some Readme changes.

**Comment by smudge202** [comment]
See #5
