### ISSUE TITLE
The 'prebuild' script failed with status code 1

### ISSUE THREAD

**Issue by radwane-h** [stajs/SpecFlow.NetCore#4]
I tried the manual step but still fail :-( do you have any idea to fix it ?

Thanks

![specflowdnx](https://cloud.githubusercontent.com/assets/2054702/11570089/5adc596c-99c3-11e5-82f3-fcc7943c988b.PNG)

**Comment by stajs** [comment]
The thing that sticks out for me, is you are using `dnx451`. I've only [tested](https://github.com/stajs/SpecFlow.Dnx/tree/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final) against [`dnx46`](https://github.com/stajs/SpecFlow.Dnx/blob/master/src/SpecFlow.Dnx/project.json#L19). Is upgrading an option for you? The NuGet package will only have `dnx46` bits in it.

I'm happy to take a PR for `dnx451`, or if I get time I might try and add it later.

The other thing I noticed, is your `dnu` version is later than what I have, but I don't think that will matter.

**Comment by stajs** [comment]
I've updated the README to show the supported framework.

**Comment by radwane-h** [comment]
It is weird, because I ran dnvm upgrade. I tried with dnvm upgrade -u and still have 451 :/

**Comment by smudge202** [comment]
Upgrade your web tools. Just download from https://get.asp.net and it'll upgrade you to the latest templates. It also handles dnx, dnvm, and dnu upgrades.

If you've moved onto the unstable branch then the runner will not work for you.

Also, to confirm something @stajs mentioned; the runner will not work (will not resolve as a dependency) of a `dnx451` target. You'll need to migrate to `dnx46` which this package supports, as well as `xunit` and the `xunit.runner.dnx`.

**Comment by stajs** [comment]
Good clarifications from @smudge202.

@dotnetstation Does the [sample](https://github.com/stajs/SpecFlow.Dnx/tree/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final) work for you?

A few other things to consider.

Firstly, `dnvm upgrade` will/should install the latest available runtime machine-wide. If you do a `dnvm list` you can see what you have installed and what is set as the default runtime. I haven't bothered with RC1 update 1 yet, so for me my default is RC 1:

![image](https://cloud.githubusercontent.com/assets/2253814/11574384/44227e06-9a70-11e5-97b6-ca699732b062.png)

Secondly, a `dnvm upgrade` won't change your `global.json`. If you have one, make sure it isn't specifying a different runtime to use ([see example from sample](https://github.com/stajs/SpecFlow.Dnx/blob/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final/global.json#L3)).

Thirdly, again a `dnvm upgrade` won't change your `project.json`. Make sure it is specifying `dnx46` (since `dnx451` is not yet supported, [see example from sample](https://github.com/stajs/SpecFlow.Dnx/blob/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final/Sample.Website.Tests/project.json#L10)).

**Comment by radwane-h** [comment]
I already installed Asp.net 5 RC :-/ 
Well your sample works in my machine, It is a good start, thanks for your explanation guys :-)

**Comment by stajs** [comment]
Okay, good luck!

**Comment by stajs** [comment]
`dnx451` support as of [`alpha9`](https://www.nuget.org/packages/SpecFlow.Dnx/1.0.0-alpha9).

**Comment by radwane-h** [comment]
I have some troubles with Visual Studio 2015, but in command line it works fine

**Comment by stajs** [comment]
Are you "producing output" (see README)?
